SOURCES/webkaos.conf
You should use `xtra/pagespeed-enabled.conf` instead of `xtra/pagespeed_enabled.conf`.
=> webkaos.conf: fixed a typo.

SOURCES/webkaos.conf, SOURCES/webkaos.patch, readme.md, webkaos-centos6.spec, webkaos-centos7.spec
* Nginx updated to 1.11.1 with CVE-2016-4450 fix
* Lua module updated to 0.10.5
* MoreHeaders module updated to 0.30
* Fixed arch for webkaos-nginx package
* Nginx updated to 1.11.1 with CVE-2016-4450 fix
* Lua module updated to 0.10.5
* MoreHeaders module updated to 0.30
* PageSpeed updated to 1.11.33.2
* Fixed arch for webkaos-nginx package
=> Version 1.11.1

SOURCES/webkaos-dynamic-tls-records.patch, SOURCES/webkaos.patch, webkaos-centos6.spec, webkaos-centos7.spec
* Added [patch](https://blog.cloudflare.com/optimizing-tls-over-tcp-to-reduce-latency/) for dynamic TLS records size
=> Version 1.11.1.1

SOURCES/ssl-wildcard.conf, webkaos-centos6.spec, webkaos-centos7.spec
=> Version 1.11.3.1

SOURCES/webkaos.patch, patch-check.sh, webkaos-centos6.spec, webkaos-centos7.spec
* Nginx updated to 1.11.4
* OpenSSL updated to 1.0.2i
* PageSpeed updated to 1.11.33.4
* Lua module updated to 0.10.6
* More Headers module updated to 0.31
=> Version 1.11.4

SOURCES/webkaos.init, readme.md, webkaos-centos6.spec, webkaos-centos7.spec
* Lua module updated to 0.10.7
* More Headers module updated to 0.32
* Added `request_id` to log output and `X-Request-ID` header
=> Version 1.11.5.1

SOURCES/webkaos-debug.service, SOURCES/webkaos.init, SOURCES/webkaos.service, webkaos-centos6.spec, webkaos-centos7.spec
* Added fix for [CVE-2016-1247](http://legalhackers.com/advisories/Nginx-Exploit-Deb-Root-PrivEsc-CVE-2016-1247.html)
* `WK-9` Dynamic modules support
* Added fix for [CVE-2016-1247](http://legalhackers.com/advisories/Nginx-Exploit-Deb-Root-PrivEsc-CVE-2016-1247.html)
* `WK-8` Systemd support
* `WK-9` Dynamic modules support
=> Version 1.11.5.2

SOURCES/boring.patch, SOURCES/webkaos.patch, patch-proc.sh, webkaos-centos6.spec, webkaos-centos7.spec
* `WK-10` Nginx updated to 1.11.6
* `WK-10` Nginx updated to 1.11.6
* Patch processing script improved
=> Version 1.11.6

SOURCES/webkaos.patch, SOURCES/webkaos.service, webkaos-centos6.spec, webkaos-centos7.spec
* Nginx updated to 1.11.8
* PageSpeed updated to 1.12.34.2
* PCRE updated to 8.40
* zlib updated to 1.2.11
* `[WK-11]`Fixed bug in systemd unit file
=> Version 1.11.8

SOURCES/webkaos.patch, webkaos-centos6.spec, webkaos-centos7.spec
* Webserver name removed from error pages for security purposes
=> Version 1.11.10.1

SOURCES/webkaos.patch
* Webserver name removed from error pages for security purposes
=> Version 1.11.10.1 (with fix)

SOURCES/webkaos.conf, webkaos-centos.spec
* Improved SSL preferences
* Enabled dynamic TLS records by default
* PCRE JIT enabled by default
=> Version 1.11.12.1

SOURCES/webkaos-http2-spdy.patch, readme.md, webkaos.spec
* Added CloudFlare's patch for SPDY support
=> Version 1.13.4.1

SOURCES/webkaos.patch, webkaos.spec
* Added support of HTTP status code 418 (I'm a teapot)
=> Version 1.13.4.2

SOURCES/webkaos.patch, webkaos.spec
=> Version 1.13.5

SOURCES/mime.patch, SOURCES/webkaos.init, SOURCES/webkaos.patch, webkaos.spec
=> Version 1.13.6

SOURCES/common.conf, readme.md, webkaos.spec
* Added `--with-compat` option for improved compatibility with dynamic modules
* Improved extended preferences
=> Version 1.13.6.2

SOURCES/webkaos-http2-spdy.patch, SOURCES/webkaos.patch, webkaos.spec
* Nginx updated to 1.13.9
* HTTP2+SPDY patch recreated for compatibility with latest version
=> Version 1.13.9

SOURCES/common.conf, SOURCES/webkaos.conf, webkaos.spec
* Improved configuration files
=> Version 1.13.9.1

.travis.yml, .travis/rpmlint.conf, SOURCES/webkaos.patch, patch-proc.sh, webkaos.spec
* Nginx updated to 1.13.10
* PCRE updated to 8.42
=> Version 1.13.10

SOURCES/webkaos.patch, webkaos.spec
=> Version 1.13.11

SOURCES/webkaos.patch, webkaos.spec
* Nginx updated to 1.13.12
* BoringSSL updated to the latest version
=> Version 1.13.12

SOURCES/common.conf, SOURCES/webkaos.conf, SOURCES/webkaos.init, SOURCES/webkaos.patch, webkaos.spec
- Nginx updated to 1.14.0
- Lua module updated to 0.10.13
- BoringSSL updated to latest version
- Improved default settings
=> Version 1.14.0

SOURCES/mime.patch, SOURCES/webkaos.patch, webkaos.spec
* Nginx updated to 1.15.1
* BoringSSL updated to the latest version
=> Version 1.15.1

README.md, SOURCES/webkaos.conf, webkaos.spec
* Dropped `TLSv1` support
* Dropped support of `TLS_RSA_WITH_AES_256_CBC_SHA` and `TLS_RSA_WITH_AES_128_CBC_SHA`
=> Version 1.15.1.1

SOURCES/webkaos.patch, webkaos.spec
=> Version 1.15.2

SOURCES/webkaos-dynamic-tls-records.patch, SOURCES/webkaos.patch, webkaos.spec
* Nginx updated to 1.15.3
* BoringSSL updated to the latest version
* Updated dynamic TLS records patch for compatibility with the latest version
=> Version 1.15.3

SOURCES/webkaos.patch, webkaos.spec
=> Version 1.15.5

README.md, webkaos.spec
=> Version 1.15.5.1

SOURCES/webkaos.patch, webkaos.spec
- Nginx updated to 1.15.7
- BoringSSL updated
=> Version 1.15.7

SOURCES/webkaos.init, webkaos.spec
=> Version 1.17.0.1

README.md, SOURCES/webkaos.patch, webkaos.spec
- Nginx updated to 1.17.1
- LuaJIT updated to 2.1-20190626
- Lua module updated to 0.10.15
- Using cmake3 for BoringSSL build
=> Version 1.17.1

SOURCES/webkaos.conf, SOURCES/webkaos.patch, webkaos.spec
=> Version 1.17.2

SOURCES/resty-core-disable.patch, webkaos.spec
* `resty-core` disabled by default
=> Version 1.17.2.1

SOURCES/webkaos.patch, webkaos.spec
- Nginx updated to 1.17.4
- Switched to official ngx_brotli repository
=> Version 1.17.4

.bibop/modules.conf, .bibop/webkaos-c6.recipe, .bibop/webkaos-c7.recipe, SOURCES/webkaos.conf, SOURCES/webkaos.patch, webkaos.spec
* Nginx updated to 1.17.7
* Improved bibop tests
* Dropped TLS 1.1 support from the default config
=> Version 1.17.7

SOURCES/webkaos.patch, centos6.docker, centos7.docker, patch-proc.sh, webkaos.spec
- Nginx updated to `1.17.8`
- LuaJIT updated to `2.1-20200102`
- PCRE updated to `8.44`
- Using DevToolSet 7 for build
- Improvements for patch processing script
=> Version 1.17.8

SOURCES/webkaos.patch, centos6.docker, centos7.docker, webkaos.spec
=> Version 1.17.9

webkaos.spec
* Added `http_auth_request_module`
=> Version 1.17.9.1

SOURCES/webkaos-dynamic-tls-records.patch, SOURCES/webkaos.init, SOURCES/webkaos.patch, centos7.docker, webkaos.spec
- Nginx updated to `1.19.0`
- Updated dynamic TLS records patch for compatibility with the latest version
- Fixed minor bug in init script
=> Version 1.19.0

SOURCES/webkaos.patch, webkaos.spec
- Added dark mode support to error pages
- Fixed bug with unclosed if condition in `postun` scriptlet
=> Version 1.19.0.1

.bibop/webkaos-c7.recipe, .bibop/webkaos.conf, SOURCES/webkaos.patch, webkaos.spec
- Nginx updated to `1.19.3`
- brotli module updated to the latest stable release
- LuaJIT updated to `2.1-20201012-2`
- NAXSI module updated to `1.1a`
- Improved bibop recipe
- Fixed bug with using system LuaJIT instead of OpenResty's fork
=> Version 1.19.3

SOURCES/webkaos-dynamic-tls-records.patch, SOURCES/webkaos.patch, patch-proc.sh, webkaos.spec
- Nginx updated to `1.19.4`
- LuaJIT updated to `2.1-20201027`
- NAXSI module updated to `1.3`
- Improved patch processing script
=> Version 1.19.4

SOURCES/webkaos.patch, centos7.docker, webkaos.spec
=> Version 1.19.9

.github/workflows/ci.yml, SOURCES/webkaos.conf, centos7.docker
* Improved Dockerfile
* Improved GitHub workflow
* Added log format for streams
=> Maintenance update

.github/workflows/ci.yml, LICENSE, README.md, SOURCES/mime.patch, SOURCES/webkaos.patch, webkaos.spec
- Nginx updated to `1.21.4`
- lua-nginx-module updated to `0.10.20`
- Updated link to PCRE
=> Version 1.21.4

SOURCES/webkaos.conf, webkaos.spec
* Removed duplicate of `$http_referer` from `timed_combined` log format
=> Version 1.21.4.1

.docker/centos7-unprivileged.docker, .docker/centos7.docker, .docker/entrypoint.sh, .docker/entrypoint_test.sh, .github/workflows/ci.yml, README.md, SOURCES/webkaos-docker-unprivileged.conf, SOURCES/webkaos-docker.conf
* Added new unprivileged image (`centos7-unprivileged`)
* New entrypoint script with automatic `worker_processes` and `server_names_hash_bucket_size` tuning
* Unit tests for entrypoint script
* Special configurations for Docker images
=> Brand new Docker images with improved k8s support

.github/workflows/ci.yml, SOURCES/webkaos.patch, webkaos.spec
- Nginx updated to `1.21.5`
- BoringSSL updated to the latest stable version
- LuaJIT updated to `2.1-20211210`
=> Version 1.21.5

.docker/centos7-unprivileged.docker, .docker/centos7.docker, .docker/entrypoint.sh, .docker/entrypoint_test.sh, .github/workflows/ci.yml, README.md
* Added templates support for all Docker images
* Minor entrypoint script improvements
=> Add templates support for Docker images

SOURCES/webkaos.patch, webkaos.spec
- Nginx updated to `1.21.6`
- LuaJIT updated to `2.1-20220111`
=> Version 1.21.6

webkaos.spec
- Added `ngx_http_geoip_module` module build
=> Version 1.28.0+1
